export { ok, fail, type ApiResponse } from "./response";
export { computeMatchScore } from "./match-score";
export {
  handleCompaniesIndia,
  handleCompanyStats,
  handleDigest,
  handleAffiliateSettingsGet,
  handleAffiliateSettingsUpdate,
  handleFeaturedCreateOrder,
  handleGetApplications,
  handleGigAffiliateUpdate,
  handleGigSlugs,
  handleGigsGet,
  handleGoRedirect,
  handleHealth,
  handleHome,
  handleIngest,
  handleInternalStats,
  handleJobBySlug,
  handleJobSlugs,
  handleJobsGet,
  handleRazorpayWebhook,
  handleRecommendedJobs,
  handleSubscribe,
  handleUpsertProfile,
  handleGetProfile,
  handleToggleSavedJob,
  handleGetSavedJobs,
  handleUpsertApplication,
  handleSubmitSalary,
  handleSalaryByRole,
  handleSalaryRoles,
  handleCompaniesIndia,
  handleGetCompanyBySlug,
} from "./handlers";
export { getAffiliateSettingsForAdmin, loadAffiliateSettings } from "./affiliate-config";
